# Generated by Django 4.1.1 on 2022-09-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
