# Generated by Django 4.1.1 on 2022-09-27 17:08

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_pub_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
